import { User, DriverProfile, Route } from "../types/routeshare";

export const mockDrivers: Array<User & { driverProfile: DriverProfile }> = [
  {
    id: "driver_1",
    firstName: "John",
    lastName: "Davis",
    phone: "+1234567890",
    email: "john.davis@email.com",
    profilePhoto: "https://i.pravatar.cc/150?img=12",
    userType: "driver",
    verificationLevel: "community",
    rating: 4.9,
    totalTrips: 127,
    createdAt: "2024-01-15T00:00:00Z",
    driverProfile: {
      userId: "driver_1",
      vehicleMake: "Ford",
      vehicleModel: "F-150",
      vehicleYear: 2020,
      vehicleColor: "Blue",
      licensePlate: "ABC-1234",
      seats: 4,
      licenseVerified: true,
      insuranceVerified: true,
      backgroundCheckStatus: "approved",
      isActive: true,
      totalEarnings: 3240.5,
    },
  },
  {
    id: "driver_2",
    firstName: "Sarah",
    lastName: "Mitchell",
    phone: "+1234567891",
    email: "sarah.m@email.com",
    profilePhoto: "https://i.pravatar.cc/150?img=47",
    userType: "driver",
    verificationLevel: "premium",
    rating: 5.0,
    totalTrips: 89,
    createdAt: "2024-02-20T00:00:00Z",
    driverProfile: {
      userId: "driver_2",
      vehicleMake: "Toyota",
      vehicleModel: "RAV4",
      vehicleYear: 2021,
      vehicleColor: "Silver",
      licensePlate: "XYZ-5678",
      seats: 4,
      licenseVerified: true,
      insuranceVerified: true,
      backgroundCheckStatus: "approved",
      isActive: true,
      totalEarnings: 2150.0,
    },
  },
  {
    id: "driver_3",
    firstName: "Robert",
    lastName: "Thompson",
    phone: "+1234567892",
    email: "rob.t@email.com",
    profilePhoto: "https://i.pravatar.cc/150?img=33",
    userType: "driver",
    verificationLevel: "community",
    rating: 4.8,
    totalTrips: 203,
    createdAt: "2023-11-10T00:00:00Z",
    driverProfile: {
      userId: "driver_3",
      vehicleMake: "Chevrolet",
      vehicleModel: "Silverado",
      vehicleYear: 2019,
      vehicleColor: "Red",
      licensePlate: "DEF-9012",
      seats: 5,
      licenseVerified: true,
      insuranceVerified: true,
      backgroundCheckStatus: "approved",
      isActive: true,
      totalEarnings: 5890.75,
    },
  },
];

export const mockRoutes: Route[] = [
  {
    id: "route_1",
    driverId: "driver_1",
    origin: {
      latitude: 38.895,
      longitude: -77.037,
      address: "Millville Town Center",
    },
    destination: {
      latitude: 38.92,
      longitude: -77.05,
      address: "County Medical Center",
    },
    departureTime: new Date(Date.now() + 10 * 60000).toISOString(),
    availableSeats: 3,
    isRecurring: false,
    status: "active",
    estimatedDuration: 25,
    distance: 18.5,
    createdAt: new Date().toISOString(),
  },
  {
    id: "route_2",
    driverId: "driver_2",
    origin: {
      latitude: 38.89,
      longitude: -77.04,
      address: "Downtown Millville",
    },
    destination: {
      latitude: 38.915,
      longitude: -77.045,
      address: "Riverside Shopping Plaza",
    },
    departureTime: new Date(Date.now() + 5 * 60000).toISOString(),
    availableSeats: 2,
    isRecurring: true,
    recurrencePattern: "daily",
    status: "active",
    estimatedDuration: 20,
    distance: 15.2,
    createdAt: new Date().toISOString(),
  },
  {
    id: "route_3",
    driverId: "driver_3",
    origin: {
      latitude: 38.898,
      longitude: -77.035,
      address: "Oak Street",
    },
    destination: {
      latitude: 38.925,
      longitude: -77.055,
      address: "County Hospital",
    },
    departureTime: new Date(Date.now() + 15 * 60000).toISOString(),
    availableSeats: 4,
    isRecurring: false,
    status: "active",
    estimatedDuration: 30,
    distance: 22.3,
    createdAt: new Date().toISOString(),
  },
];
